"""
models.py — Typed data contracts for the OpenEnv Creative Auctioneer.

All tensors / vectors are represented as plain Python types so the environment
stays framework-agnostic (no hard dependency on PyTorch at this layer).
"""

from typing import Optional
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Observation  (what the agent *sees* each step)
# ---------------------------------------------------------------------------

class Observation(BaseModel):
    # ── Temporal ──────────────────────────────────────────────────────────
    hour_of_day: int = Field(..., ge=0, le=23,
        description="Current hour of the 24-hour campaign cycle (0–23).")

    # ── Budget / Pacing ────────────────────────────────────────────────────
    remaining_budget: float = Field(...,
        description="Remaining daily budget in USD.")
    spent_so_far: float = Field(default=0.0,
        description="Cumulative spend in USD up to this step.")

    # ── Contextual Signals (Privacy-Native — no user IDs) ──────────────────
    current_context: str = Field(...,
        description="Content category the audience is currently consuming "
                    "(e.g. 'Fitness', 'Tech', 'Fashion', 'Gaming').")
    viral_trend: str = Field(...,
        description="Current cultural viral token surfaced from Reels "
                    "(e.g. 'Quiet Luxury', 'Eco-Friendly', 'Cyberpunk', 'Minimalism').")

    # ── Market Signals ─────────────────────────────────────────────────────
    market_pressure: float = Field(default=0.5, ge=0.0, le=1.0,
        description="Normalised indicator of how competitive the auction is "
                    "this hour (0 = cheap, 1 = very expensive).")

    # ── Session State ──────────────────────────────────────────────────────
    ads_shown_this_session: int = Field(default=0,
        description="Number of ads already shown; drives the fatigue penalty.")
    fatigue_level: float = Field(default=0.0, ge=0.0, le=1.0,
        description="Accumulated user-fatigue penalty (0 = fresh, 1 = fully fatigued).")

    # ── Performance Feedback (delayed by 1 step) ───────────────────────────
    last_ctr: float = Field(default=0.0, ge=0.0, le=1.0,
        description="CTR returned by the User Simulator on the previous step.")
    cumulative_revenue: float = Field(default=0.0,
        description="Total revenue earned so far.")


# ---------------------------------------------------------------------------
# Action  (what the agent *does* each step)
# ---------------------------------------------------------------------------

class Action(BaseModel):
    # Continuous: auction bid
    bid_price: float = Field(..., ge=0.0,
        description="Bid submitted to the RTB auction in USD.")

    # Discrete: creative selection
    headline_id: int = Field(..., ge=0, le=5,
        description="Index into the Headlines Catalog (0–5).")
    creative_id: int = Field(..., ge=0, le=5,
        description="Index into the Creatives Catalog (0–5).")

    # Optional free-text caption (used in hard_assembly grading via CLIP/semantic sim)
    generated_caption: Optional[str] = Field(default=None,
        description="Free-form caption generated by the agent for hard_assembly. "
                    "Leave None for easy/medium tasks.")


# ---------------------------------------------------------------------------
# Per-step Info  (returned alongside reward; not part of observation)
# ---------------------------------------------------------------------------

class Info(BaseModel):
    task_id: str
    current_step: int
    total_revenue: float
    clearing_price: float = Field(default=0.0,
        description="The winning competitor bid price this step.")
    auction_won: bool = Field(default=False,
        description="Whether the agent won the auction this step.")
    raw_ctr: float = Field(default=0.0,
        description="CTR before fatigue penalty applied.")
    adjusted_ctr: float = Field(default=0.0,
        description="CTR after fatigue penalty.")

    # ── Per-task grader scores ────────────────────────────────────────────
    task_score: float = Field(..., ge=0.0, le=1.0,
        description="Final 0.0–1.0 task-completion score.")

    # Level-specific sub-scores (populated per task_id)
    headline_alignment_score: float = Field(default=0.0, ge=0.0, le=1.0,
        description="[easy_headline] CTR_selected / CTR_best for this context.")
    pacing_score: float = Field(default=0.0, ge=0.0, le=1.0,
        description="[medium_pacing] Budget-smoothness and peak-hour survival bonus.")
    clip_similarity_score: float = Field(default=0.0, ge=0.0, le=1.0,
        description="[hard_assembly] Cosine similarity between caption and viral token.")
